services:

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=secret
    ports:
      - 8081:8081
    depends_on:
      - redis
  db:
    image: mcr.microsoft.com/mssql/server
    environment:
      SA_PASSWORD: "secret"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
      MSSQL_USER: "appuser"
      MSSQL_PASSWORD: "secret"
      MSSQL_DB: "MarketManagement"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/data     
    
volumes:
  redis-data:
  mssql-data: